all:
  children:
    prod:
      hosts:
        my_host_00:
          ansible_host: 192.168.8.91
          host_name: "Eva-01"
    dev:
      hosts:
        my_host_01:
          ansible_host: 192.168.8.90
          host_name: "Eva-00"
