- name: "Crear directorios de contenedores"
  become: false
  ansible.builtin.file:
    path: "{{ podman_server_vol_path }}/{{ item.name }}"
    state: directory
    mode: '0755'
  loop:
    - name: "syncthing"
    - name: "gitea"
    - name: "firefly"

- name: "Creacion de redes quadlet"
  become: false
  containers.podman.podman_network:
    state: quadlet
    name: "{{ item.name }}"
  loop:
    - name: "gitea-app"
    - name: "syncthing"

- name: "Creacion de quadlets"
  become: false
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: quadlet
    ports: "{{ item.ports | default(omit) }}"
    volume: "{{ item.volumes | default(omit) }}"
    network: "{{ item.network | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    quadlet_options: "{{ item.quadlet_options }}"
  loop:
    - name: "gitea-app"
      image: "docker.gitea.com/gitea:latest"
      ports:
        - "3000:3000"
        - "2222:22"
      volumes:
        - "{{ podman_server_vol_path }}/gitea:/data:Z,U"
      network: "gitea-app.network"
      env:
        USER_UID: "1000"
        USER_GID: "1000"

      quadlet_options:
        - "AutoUpdate=registry"
        - "Pull=newer"
        - |
          [Service]
          Restart=allways
        - |
         [Install]
         WantedBy=default.target
    - name: "syncthing-app"
      image: "docker.io/syncthing/syncthing:latest"
      ports:
        - "8384:8384"
        - "22000:22000/tcp"
        - "22000:22000/udp"
        - "21027:21027/udp"
      volumes:
        - "{{ podman_server_vol_path }}/syncthing:/data:Z,U"
      network: "syncthing.network"
      quadlet_options:
        - "AutoUpdate=registry"
        - "Pull=newer"
        - "UserNS=keep-id:uid=1000,gid=1000"
        - |
          [Service]
          Restart=unless-stopped
        - |
         [Install]
         WantedBy=default.target
  notify: "Daemon-reload"

- name: "Iniciar quadlet gitea"
  become: false
  ansible.builtin.systemd_service:
    scope: user
    name: gitea-app
    state: started

- name: "Iniciar quadlet syncthing"
  become: false
  ansible.builtin.systemd_service:
    scope: user
    name: syncthing-app
    state: started

- name: "Activar puertos Syncthing"
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
    offline: true
  loop:
    - 8384/tcp
    - 22000/tcp
    - 22000/udp
    - 21027/udp
