#- name: "Creacion de usuarios"
#  hosts: all
#  tasks:
#    - name: "Crear usuario asuka (usuario de ansible)"
#      ansible.builtin.user:
#        name: "asuka"
#        group: "wheel"
#        comment: "Cuenta admin exclusiva para ansible"
#
#    # - name: "Copiar llave ssh para asuka"
#
#    - name: "Permitir ejecutar comandos root sin password"

- name: "Configuraciones basicas del servidor"
  hosts: all
  become: true
  tasks:
    - name: "Cambiar hostname del servidor"
      ansible.builtin.hostname:
        name: "eva-01"

    - name: "Asignar timezone"
      community.general.timezone:
        name: "{{ system_timezone }}"

    - name: "Instalar paquetes"
      ansible.builtin.dnf:
        name:
          - podman
        state: present
