# Variables para rol Base

base_items_a_instalar:
  - podman
  - firewalld
  - fail2ban
  - locate
  - neovim
  - dnf-automatic

base_root_user: "root"
### Variables para servicio dnf-automatic
base_dnf_automatic_timer_path: "/usr/lib/systemd/system/dnf-automatic.time."
base_dnf_automatic_config_path: "/etc/dnf/automatic.conf"
# Variables archivo configuracion
base_upgrade_type_config: "security"
base_reboot_config: "when-needed"
